services:
  - type: web
    name: msna-factory
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ALLOW_USERS
        value: "true"
      - key: DEFAULT_DAYS
        value: "30"
      - key: MAX_DAYS
        value: "3650"
